### ISSUE TITLE
retrieve_asset_metdata() method in MediaInsightsLambdaHelper doesn't apply operator filter.

### ISSUE THREAD

**Issue by aburkleaux-amazon** [aburkleaux-amazon/aws-media-insights-engine#15]
dataplane.retrieve_asset_metadata(asset_id, operator_name=captionsOperatorName)should return only the data for the operator, but it is returning the data for all operators.

**Comment by brandold** [comment]
Simple bugfix in the operator library:

`def retrieve_asset_metadata(self, asset_id, operator_name=None, cursor=None):
        """
        Method to retrieve metadata from the dataplane
        :param asset_id: The id of the asset
        :param operator_name: Optional parameter for filtering response to include only data
        generated by a specific operator
        :param cursor: Optional parameter for retrieving additional pages of asset metadata
        :return: Dataplane response
        """
        if operator_name:
            path = "/metadata/{asset_id}/{operator}".format(asset_id=asset_id, operator=operator_name)
            resource = "/metadata/{asset_id}/{operator_name}"
            path_params = {"asset_id": asset_id, "operator_name": operator_name}
        else:
            path = "/metadata/{asset_id}".format(asset_id=asset_id)
            resource = "/metadata/{asset_id}"
            path_params = {"asset_id": asset_id}
        method = "GET"
        query_params = {}
        if cursor:
            query_params["cursor"] = cursor
        else:
            query_params = None
        dataplane_response = self.call_dataplane(path, resource, method, None, path_params, query_params)
        return dataplane_response`

**Comment by aburkleaux-amazon** [comment]
Fixed in #47
