### ISSUE TITLE
GUI: Continue processing an asset from transcribe editing stage.

### ISSUE THREAD

**Issue by tomgilman** [aburkleaux-amazon/aws-media-insights-engine#23]

**Comment by aburkleaux-amazon** [comment]
**In the Transcribe editing view we want the following user flow:**

*Edit* button - enabled only if the workflow is in a Wait state and the CurrentStage is the WaitForTranscribeEdit.

**In editing mode:**

*Actions* menu of buttons 
- Upload and Continue 
    - uploads the edits (if there are any) to MIE using the dataplane PUT /asset/opertor API to create a new version of WebCaptions_<source_lang>
    - call new /workflow/execution/continue API to clear the Wait state
- Save
    - save edits locally so they don't get lost on webpage refresh (nice to have)

**Comment by ianwow** [comment]
Delivered in https://github.com/aburkleaux-amazon/aws-media-insights-engine/pull/53
