### ISSUE TITLE
Cloudformation fails to deploy TranscriberApp on eu-west-1 (Ireland)

### ISSUE THREAD

**Issue by sebsto** [aburkleaux-amazon/aws-media-insights-engine#5]
When using the `eu-west-1` version of the cloudformation template to deploy in `eu-west-1`, deployment fails on : 

```
TranscriberWebApp CREATE_FAILED 
s3 error: the bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.
```

**Comment by sebsto** [comment]
TranscriberWebApp fails to deploy in `us-east-1` too, error message is slightly different : 

```
TranscriberWebApp CREATE_FAILED S3 error: Access Denied For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html
```

**Comment by iandow** [comment]
Sebastien, make sure you are using the correct template for your region, like this:
 
Click the one-click deploy button from https://github.com/aburkleaux-amazon/aws-media-insights-engine:
![image](https://user-images.githubusercontent.com/1383911/78567005-df384380-77d4-11ea-9628-309b4beed785.png)

 
That will open the CloudFormation service in the AWS Console. Now, make sure you set your region to Ireland, like this:  (this part is easy to forget)
 
![image](https://user-images.githubusercontent.com/1383911/78567017-e5c6bb00-77d4-11ea-844e-e1b6ab522943.png)


 
Then click Next, fill in the AdminEmail field, click Next, Next, then check the two “I acknowledge” checkboxes and click Create Stack.

**Comment by sebsto** [comment]
Thank you Ian. I made sure I was using the correct CFN Template for the correct region.

> When using the eu-west-1 version of the cloudformation template to deploy in eu-west-1

**Comment by aburkleaux-amazon** [comment]
I think there are two issues here:

1. The Transciber app  is deprecated. We need to remove it from the deployment options.  Deploy will not work.  The new transcribe / translate is built into the "demo" app that is the default app for this template.
2. The button for Ireland in the README is loading the us-west-2 console page.  

Sebastien - try deploying using the default options.  You should only need to fill in the stack name and your e-mail address.

Load this template directly into the eu-west-1 console:  https://elementalrodeo99-eu-west-1.s3-eu-west-1.amazonaws.com/media-insights-solution/who.0.0.1/cf/media-insights-stack.template

**Comment by sebsto** [comment]
Testing the above link in `eu-west-1`  produced the same error as described here : https://github.com/aburkleaux-amazon/aws-media-insights-engine/issues/7

**Comment by sebsto** [comment]
Duplicate of https://github.com/aburkleaux-amazon/aws-media-insights-engine/issues/7
