### ISSUE TITLE
build-s3-dist.sh fails to create regional bucket

### ISSUE THREAD

**Issue by sebsto** [aburkleaux-amazon/aws-media-insights-engine#6]
I tried to build my own distribution using build-s3-dist.sh

The script says it created a regional bucket for me, but it does not 

Step to reproduce : 
- Create a deployment bucket (mie-seb)
- `./build-s3-dist.sh mie-seb v0.1 eu-west-1`

Script produces:
```
Template to deploy:
https://mie-seb-eu-west-1.s3.eu-west-1.amazonaws.com/media-insights-solution/v0.1/cf/media-insights-stack.template
```

but `mie-seb-eu-west-1.s3` does not exist : 

```
Built demo webapp
------------------------------------------------------------------------------
Copy dist to S3
------------------------------------------------------------------------------
Copying the prepared distribution to S3...
upload failed: ../../deployment/dist/check_celebrity_recognition_status.zip to s3://mie-seb-eu-west-1/media-insights-solution/v0.1/code/check_celebrity_recognition_status.zip An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist
```

**Comment by sebsto** [comment]
Creating the bucket `mie-seb-eu-west-1` manually before execution solves the problem.

**Comment by ianwow** [comment]
I moved this issue to https://github.com/awslabs/aws-media-insights-engine/issues/183.
@sebsto I'll leave it to you to close this issue.

**Comment by sebsto** [comment]
closed as it is not tracked by https://github.com/awslabs/aws-media-insights-engine/issues/183
