### ISSUE TITLE
throttling in Translate

### ISSUE THREAD

**Issue by ianwow** [aburkleaux-amazon/aws-media-insights-engine#60]
I tried uploading 9 videos with all operators enabled. 6 failed because they were throttled in Translate. 3 succeeded.

**Comment by aburkleaux-amazon** [comment]
How many languages did you hav per job?
What was your MAX_PARALLEL_WORKFLOW setting?

Your account limit is probably set to 10 concurrent Translate operations.  If you are translating 2 languages per workflow, then you need to set MAX_PARALLEL_WORKFLOWS to 5.  

In general, ACCOUNT LIMIT <= MAX_PARALLEL_WORKFLOW*NUMBER OF TRANSLATIONS.  We are setting the limit of #of translation based on a higher limit than you have in your account.

**Comment by aburkleaux-amazon** [comment]
If we want this to work in varying environments then we need to make both limits configurable.
