### ISSUE TITLE
Slow UI response when editing captions.

### ISSUE THREAD

**Issue by tomgilman** [aburkleaux-amazon/aws-media-insights-engine#62]
Editing the captions in the text box field is very slow.  I'm pressing the delete key and having to wait 3-4 seconds to see my action appear on the screen.  This was in a early version of 0.0.2.

**Comment by aburkleaux-amazon** [comment]
Sebastien suggested using a grid html widget like this to improve performance: https://www.ag-grid.com

**Comment by tomgilman** [comment]
Per @ianwow , the amount of captions in a video causes this slowdown.  Need to find a long fast talking video example.

**Comment by EddieGoynesAmazon** [comment]
Hi Ian. Is this the issue. https://github.com/vuetifyjs/vuetify/issues/6201

TLDR. Looks like lots of lag after 40 components, and person said they made a light weight component that fixed it.

**Comment by EddieGoynesAmazon** [comment]
I looked around some more and found this. He improved performance for 2000 forms to page. 
https://forum.vuejs.org/t/improve-performance-for-a-large-form/11550

Based on my calculations. I have a caption file with 72 text fields that is 4 minutes, which would make 2 hours of video right around the 2000 elements.

**Comment by ianwow** [comment]
We'll want virtual scrolling  --> vue-virtual-scroller
