### ISSUE TITLE
Cloudformation fails to deploy substack OperatorLibrary (Move to MIE)

### ISSUE THREAD

**Issue by sebsto** [aburkleaux-amazon/aws-media-insights-engine#7]
I packaged the app using the `build-s3-dist.sh` script and tried to deploy in `eu-west-1`

A nested stack "OperatorLibrary" fails to deploy with 

<img width="860" alt="image" src="https://user-images.githubusercontent.com/401798/78538646-99d63f00-77f1-11ea-85c8-b94996221ee2.png">

**Comment by aburkleaux-amazon** [comment]
Hi Sebastien,

Thanks for testing this! This will definitely help us make deployment a more smooth experience.

Media Insights Engine doesn't support multiple deployments in the same region.  I'm guessing there is another instance of MIE in this region, or there is a deployment that did not clean up completely (also a potential defect).  

Can you check if this is the only deployment you have in eu-west-1?

**Comment by sebsto** [comment]
There was only one deployment in the region

**Comment by sebsto** [comment]
I managed to find the first error reported by CFN in the Cloudwatch logs 

```
[INFO]	2020-04-06T14:56:49.92Z	de793200-1bf6-453c-9150-b4ca97a7e887	Exception An error occurred (StateMachineAlreadyExists) when calling the CreateStateMachine operation: State Machine Already Exists: 'arn:aws:states:eu-west-1:486652066693:stateMachine:_faceSearchImage'

[ERROR]	2020-04-06T14:56:49.92Z	de793200-1bf6-453c-9150-b4ca97a7e887	Error creating default stage for operation faceSearchImage: ChaliceViewError: Exception 'An error occurred (StateMachineAlreadyExists) when calling the CreateStateMachine operation: State Machine Already Exists: 'arn:aws:states:eu-west-1:486652066693:stateMachine:_faceSearchImage''

[INFO]	2020-04-06T14:56:49.153Z	de793200-1bf6-453c-9150-b4ca97a7e887	ResponseBody: 
{
    "Status": "FAILED",
    "Reason": "See the details in CloudWatch Log Stream: 2020/04/06/[$LATEST]01971258d2574ee3ba8fb81fb0b8f876",
    "PhysicalResourceId": "2020/04/06/[$LATEST]01971258d2574ee3ba8fb81fb0b8f876",
    "StackId": "arn:aws:cloudformation:eu-west-1:486652066693:stack/mie-OperatorLibrary-REGQ4BO50HVP/a869a190-7816-11ea-9d48-0a9bdcf5c20a",
    "RequestId": "3c3b5b8d-13e4-4b84-af37-c47bd38ec434",
    "LogicalResourceId": "faceSearchOperationImage",
    "Data": {
        "Message": "Exception during processing: 'ChaliceViewError: Exception 'ChaliceViewError: Exception 'An error occurred (StateMachineAlreadyExists) when calling the CreateStateMachine operation: State Machine Already Exists: 'arn:aws:states:eu-west-1:486652066693:stateMachine:_faceSearchImage''''"
    }
}
```

**Comment by sebsto** [comment]
I think I found the culprit : despite delete the stack, the Step Functions are **not** deleted 

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/401798/78575822-269dee80-782c-11ea-804e-4c7b23d5fa9c.png">

How can we clean an account in between two deployment tests ?

**Comment by sebsto** [comment]
Manually deleting left-overs from previous run helped and the OperationLibrary substack now succeeds

<img width="264" alt="image" src="https://user-images.githubusercontent.com/401798/78578752-39b2bd80-7830-11ea-9870-38fd833f2508.png">


I guess these are created by custom resources, I would suggest to implement the "delete" part of the custom resource.

**Comment by aburkleaux-amazon** [comment]
Delete is implemented in the custom resource, but I think we may be getting throttled by the step functions API or there is some other unhandled error in the custom resource.

**Comment by ianwow** [comment]
I've not been able to reproduce this. I deployed MIE with all deploy options enabled and the stack still deleted fine.

**Comment by tomgilman** [comment]
This is now being tracked in the core MIE, https://github.com/awslabs/aws-media-insights-engine/issues/190
